services:
  mongodb:
    image: mongo:6
    container_name: tuxfitness_mongodb
    env_file:
      - ./server/.env
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tuxfitness_server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: root
      DB_PASS: example
    depends_on:
      - mongodb
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: tuxfitness_client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongodb_data:
